import { useEffect, useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { Filter, BarChart3, AlertTriangle, AlertOctagon, Info, ChevronRight, ChevronDown, ChevronUp, X, Mail, Send, CheckCircle2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import DashboardLayout from "@/components/DashboardLayout";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast as sonnerToast } from "sonner";

interface WarningItem {
  severity: string;
  category: string;
  message: string;
  impact: string;
  action_required: string;
}

interface AnalysisRow {
  id: string;
  project_name: string;
  week_number: number | null;
  overall_score: number;
  overall_status: string;
  execution_team: string;
  critical: WarningItem[];
  high: WarningItem[];
  medium: WarningItem[];
}

function getWarnings(warnings: any[], severity: string): WarningItem[] {
  if (!Array.isArray(warnings)) return [];
  return warnings.filter((w: any) => w?.severity === severity);
}

function getScoreColor(score: number) {
  if (score >= 75) return "text-success";
  if (score >= 50) return "text-warning";
  return "text-critical";
}

function getStatusBadge(status: string) {
  const map: Record<string, { label: string; cls: string }> = {
    healthy: { label: "Healthy", cls: "bg-success/15 text-success" },
    at_risk: { label: "At Risk", cls: "bg-warning/15 text-warning" },
    critical: { label: "Critical", cls: "bg-critical/15 text-critical" },
  };
  const s = map[status] || map.critical;
  return <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-full ${s.cls}`}>{s.label}</span>;
}

function WarningCell({ items, colorClass }: { items: WarningItem[]; colorClass: string }) {
  const [expanded, setExpanded] = useState(false);

  if (items.length === 0) {
    return <span className="text-muted-foreground font-bold">0</span>;
  }

  return (
    <div className="text-left">
      <button
        onClick={(e) => { e.stopPropagation(); setExpanded(!expanded); }}
        className={`font-bold ${colorClass} flex items-center gap-1 mx-auto hover:underline`}
      >
        {items.length}
        {expanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
      </button>
      {expanded && (
        <div className="mt-2 space-y-1.5 text-left" onClick={(e) => e.stopPropagation()}>
          {items.map((w, i) => (
            <div key={i} className="text-[11px] leading-tight p-2 rounded-lg bg-muted/40 border border-border/50">
              <p className={`font-semibold ${colorClass} mb-0.5`}>{w.category}</p>
              <p className="text-foreground/80">{w.message}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function buildEmailBody(row: AnalysisRow): string {
  const lines: string[] = [];
  lines.push(`Project: ${row.project_name}`);
  lines.push(`Week: ${row.week_number ?? "—"}`);
  lines.push(`Execution Team: ${row.execution_team}`);
  lines.push(`Health Score: ${row.overall_score}/100 (${row.overall_status.replace("_", " ")})`);
  lines.push("");

  const addSection = (title: string, items: WarningItem[]) => {
    if (items.length === 0) return;
    lines.push(`━━ ${title} (${items.length}) ━━`);
    items.forEach((w, i) => {
      lines.push(`${i + 1}. [${w.category}]`);
      lines.push(`   ${w.message}`);
      if (w.impact) lines.push(`   Impact: ${w.impact}`);
      if (w.action_required) lines.push(`   Action Required: ${w.action_required}`);
      lines.push("");
    });
  };

  addSection("🔴 Critical Findings", row.critical);
  addSection("🟠 High Priority Findings", row.high);
  addSection("🟡 Medium Priority Findings", row.medium);

  lines.push("—");
  lines.push("This report was generated by WPR Audit.");
  return lines.join("\n");
}

function EmailDraftDialog({ row, open, onClose }: { row: AnalysisRow | null; open: boolean; onClose: () => void }) {
  const [to, setTo] = useState("");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [sent, setSent] = useState(false);

  useEffect(() => {
    if (row && open) {
      setTo("");
      setSent(false);
      setSubject(`WPR Audit Report — ${row.project_name} (Week ${row.week_number ?? "—"}) | Score: ${row.overall_score}/100`);
      setBody(buildEmailBody(row));
    }
  }, [row, open]);

  const handleSend = () => {
    if (!to.trim()) {
      sonnerToast.error("Please enter a recipient email address.");
      return;
    }
    setSent(true);
  };

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onClose(); }}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        {sent ? (
          <div className="flex flex-col items-center justify-center py-12 gap-4">
            <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: "spring", stiffness: 200, damping: 15 }}
              className="w-16 h-16 rounded-full bg-success/15 flex items-center justify-center">
              <CheckCircle2 className="w-8 h-8 text-success" />
            </motion.div>
            <motion.h3 initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
              className="text-xl font-bold text-foreground">Email Sent Successfully!</motion.h3>
            <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.35 }}
              className="text-sm text-muted-foreground text-center max-w-sm">
              The WPR audit report for <strong>{row?.project_name}</strong> has been sent to <strong>{to}</strong>.
            </motion.p>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}>
              <Button onClick={onClose} className="mt-2">Close</Button>
            </motion.div>
          </div>
        ) : (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Mail className="w-5 h-5 text-primary" />
                Draft Email Report
              </DialogTitle>
            </DialogHeader>

            <div className="space-y-4 mt-2">
              <div>
                <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1 block">To</label>
                <Input
                  type="email"
                  placeholder="recipient@example.com"
                  value={to}
                  onChange={(e) => setTo(e.target.value)}
                />
              </div>

              <div>
                <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1 block">Subject</label>
                <Input
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                />
              </div>

              <div>
                <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1 block">Body</label>
                <Textarea
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  className="min-h-[280px] font-mono text-xs leading-relaxed"
                />
              </div>

              {/* Summary badges */}
              {row && (
                <div className="flex items-center gap-3 text-xs">
                  {row.critical.length > 0 && (
                    <span className="flex items-center gap-1 px-2 py-1 rounded-full bg-critical/10 text-critical font-semibold">
                      <AlertOctagon className="w-3 h-3" /> {row.critical.length} Critical
                    </span>
                  )}
                  {row.high.length > 0 && (
                    <span className="flex items-center gap-1 px-2 py-1 rounded-full bg-warning/10 text-warning font-semibold">
                      <AlertTriangle className="w-3 h-3" /> {row.high.length} High
                    </span>
                  )}
                  {row.medium.length > 0 && (
                    <span className="flex items-center gap-1 px-2 py-1 rounded-full bg-blue-400/10 text-blue-400 font-semibold">
                      <Info className="w-3 h-3" /> {row.medium.length} Medium
                    </span>
                  )}
                </div>
              )}

              <div className="flex justify-end gap-3 pt-2">
                <Button variant="outline" onClick={onClose}>Cancel</Button>
                <Button onClick={handleSend} className="gap-2">
                  <Send className="w-4 h-4" /> Send Email
                </Button>
              </div>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}

export default function AnalysisDashboard() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [rows, setRows] = useState<AnalysisRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedProject, setSelectedProject] = useState("all");
  const [selectedWeeks, setSelectedWeeks] = useState<number[]>([]);
  const [emailRow, setEmailRow] = useState<AnalysisRow | null>(null);

  useEffect(() => {
    supabase
      .from("wpr_analyses")
      .select("id, project_name, week_number, overall_score, overall_status, analysis_data")
      .order("project_name")
      .order("week_number", { ascending: false })
      .then(({ data, error }) => {
        if (error) {
          toast({ title: "Failed to load analyses", description: error.message, variant: "destructive" });
          setLoading(false);
          return;
        }
        const mapped: AnalysisRow[] = (data || []).map((d: any) => {
          const ad = d.analysis_data || {};
          const warnings = ad.warnings || [];
          return {
            id: d.id,
            project_name: d.project_name,
            week_number: d.week_number,
            overall_score: d.overall_score,
            overall_status: d.overall_status,
            execution_team: ad.project_details?.execution_team || "—",
            critical: getWarnings(warnings, "critical"),
            high: getWarnings(warnings, "high"),
            medium: getWarnings(warnings, "medium"),
          };
        });
        setRows(mapped);
        setLoading(false);
      });
  }, []);

  const projects = useMemo(() => [...new Set(rows.map(r => r.project_name))].sort(), [rows]);
  const weeks = useMemo(() => {
    return [...new Set(rows.filter(r => r.week_number).map(r => r.week_number!))].sort((a, b) => b - a);
  }, [rows]);

  const toggleWeek = (w: number) => {
    setSelectedWeeks(prev => prev.includes(w) ? prev.filter(x => x !== w) : [...prev, w]);
  };

  const filtered = useMemo(() => {
    return rows.filter(r => {
      if (selectedProject !== "all" && r.project_name !== selectedProject) return false;
      if (selectedWeeks.length > 0 && !selectedWeeks.includes(r.week_number!)) return false;
      return true;
    });
  }, [rows, selectedProject, selectedWeeks]);

  const hasFilters = selectedProject !== "all" || selectedWeeks.length > 0;

  return (
    <DashboardLayout>
      <div className="max-w-7xl mx-auto px-6 py-10">
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
          <div className="flex items-center gap-3 mb-1">
            <BarChart3 className="w-6 h-6 text-primary" />
            <h1 className="text-2xl font-bold text-foreground">Consolidated Analysis</h1>
          </div>
          <p className="text-muted-foreground mb-6 ml-9">Overview of all analyzed projects and their health status.</p>
        </motion.div>

        {/* Filters */}
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }} className="flex flex-wrap items-center gap-3 mb-6">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Filter className="w-4 h-4" />
            <span>Filter:</span>
          </div>
          <Select value={selectedProject} onValueChange={setSelectedProject}>
            <SelectTrigger className="w-[200px] h-9">
              <SelectValue placeholder="All Projects" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Projects</SelectItem>
              {projects.map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}
            </SelectContent>
          </Select>

          {/* Multi-week selector */}
          <Popover>
            <PopoverTrigger asChild>
              <Button variant="outline" className="h-9 min-w-[140px] justify-between text-sm font-normal">
                {selectedWeeks.length === 0
                  ? "All Weeks"
                  : selectedWeeks.length === 1
                    ? `Week ${selectedWeeks[0]}`
                    : `${selectedWeeks.length} weeks`}
                <ChevronDown className="w-3.5 h-3.5 ml-2 opacity-50" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[180px] p-2" align="start">
              <div className="space-y-1 max-h-[200px] overflow-y-auto">
                {weeks.map(w => (
                  <label key={w} className="flex items-center gap-2 px-2 py-1.5 rounded-md hover:bg-muted/50 cursor-pointer text-sm">
                    <Checkbox
                      checked={selectedWeeks.includes(w)}
                      onCheckedChange={() => toggleWeek(w)}
                    />
                    Week {w}
                  </label>
                ))}
              </div>
              {selectedWeeks.length > 0 && (
                <button onClick={() => setSelectedWeeks([])} className="text-xs text-primary hover:underline mt-2 px-2">
                  Clear
                </button>
              )}
            </PopoverContent>
          </Popover>

          {hasFilters && (
            <button onClick={() => { setSelectedProject("all"); setSelectedWeeks([]); }} className="text-xs text-primary hover:underline flex items-center gap-1">
              <X className="w-3 h-3" /> Clear all
            </button>
          )}
        </motion.div>

        {/* Table */}
        {loading ? (
          <div className="flex items-center gap-3 text-muted-foreground py-12 justify-center">
            <div className="w-2 h-2 rounded-full bg-primary animate-pulse-dot" />
            Loading...
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-16">
            <BarChart3 className="w-10 h-10 text-muted-foreground/40 mx-auto mb-3" />
            <p className="text-muted-foreground">
              {rows.length === 0 ? "No analyses found. Analyze projects first." : "No results match your filters."}
            </p>
          </div>
        ) : (
          <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
            <div className="glass-card rounded-xl overflow-hidden border border-border">
              <Table>
                <TableHeader>
                  <TableRow className="bg-muted/30">
                    <TableHead className="font-semibold">Project Name</TableHead>
                    <TableHead className="font-semibold text-center">Week</TableHead>
                    <TableHead className="font-semibold">Execution Team</TableHead>
                    <TableHead className="font-semibold text-center">
                      <span className="flex items-center justify-center gap-1">
                        <AlertOctagon className="w-3.5 h-3.5 text-critical" /> Critical
                      </span>
                    </TableHead>
                    <TableHead className="font-semibold text-center">
                      <span className="flex items-center justify-center gap-1">
                        <AlertTriangle className="w-3.5 h-3.5 text-warning" /> High
                      </span>
                    </TableHead>
                    <TableHead className="font-semibold text-center">
                      <span className="flex items-center justify-center gap-1">
                        <Info className="w-3.5 h-3.5 text-blue-400" /> Medium
                      </span>
                    </TableHead>
                    <TableHead className="font-semibold text-center">Health Score</TableHead>
                    <TableHead className="font-semibold text-center w-20">Email</TableHead>
                    <TableHead className="w-8"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filtered.map((r) => (
                    <TableRow
                      key={r.id}
                      className="cursor-pointer hover:bg-muted/20 transition-colors align-top"
                      onClick={() => navigate(`/report/${r.id}`)}
                    >
                      <TableCell className="font-medium">{r.project_name}</TableCell>
                      <TableCell className="text-center">
                        {r.week_number ? (
                          <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded-full bg-primary/10 text-primary">
                            W{r.week_number}
                          </span>
                        ) : "—"}
                      </TableCell>
                      <TableCell className="text-muted-foreground">{r.execution_team}</TableCell>
                      <TableCell className="text-center">
                        <WarningCell items={r.critical} colorClass="text-critical" />
                      </TableCell>
                      <TableCell className="text-center">
                        <WarningCell items={r.high} colorClass="text-warning" />
                      </TableCell>
                      <TableCell className="text-center">
                        <WarningCell items={r.medium} colorClass="text-blue-400" />
                      </TableCell>
                      <TableCell className="text-center">
                        <div className="flex items-center justify-center gap-2">
                          <span className={`text-lg font-bold ${getScoreColor(r.overall_score)}`}>
                            {r.overall_score}
                          </span>
                          {getStatusBadge(r.overall_status)}
                        </div>
                      </TableCell>
                      <TableCell className="text-center">
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-8 w-8 p-0 hover:bg-primary/10"
                          onClick={(e) => { e.stopPropagation(); setEmailRow(r); }}
                          title="Draft email report"
                        >
                          <Mail className="w-4 h-4 text-primary" />
                        </Button>
                      </TableCell>
                      <TableCell>
                        <ChevronRight className="w-4 h-4 text-muted-foreground" />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </motion.div>
        )}
      </div>

      <EmailDraftDialog row={emailRow} open={!!emailRow} onClose={() => setEmailRow(null)} />
    </DashboardLayout>
  );
}
